#Localizable properties associated with component.common.productListRest.pagelet2

ConfigurationParameter.Component.CSSClass.description=CSS classes of this component
ConfigurationParameter.Component.CSSClass.displayname=CSS Class
ConfigurationParameter.Component.ListItemCSSClass.description=CSS classes of the individual items
ConfigurationParameter.Component.ListItemCSSClass.displayname=List Item CSS Class
ConfigurationParameter.Component.ListItemStyle.row.displayname=Row
ConfigurationParameter.Component.ListItemStyle.tile.displayname=Tile
ConfigurationParameter.Component.ListStyle.carousel.displayname=Carousel
ConfigurationParameter.Component.ListStyle.none.displayname=None
ConfigurationParameter.Component.MaxNumberOfProducts.description=Maximum number of products to display
ConfigurationParameter.Component.MaxNumberOfProducts.displayname=Maximum Number of Products
ConfigurationParameter.Component.ProductsRestEndpoint.description=REST call to fetch product data
ConfigurationParameter.Component.ProductsRestEndpoint.displayname=Products REST Endpoint
ConfigurationParameter.Component.ProductsRestResponseMapper.description=Javascript to map the REST response 'data' to an array of SKUs<br/>\nExample:<br/>\n<tt>data.elements.map(item => item.attributes[0].value)</tt>
ConfigurationParameter.Component.ProductsRestResponseMapper.displayname=Products Data Mapper
ConfigurationParameter.Component.SlideItems.1.displayname=1
ConfigurationParameter.Component.SlideItems.2.displayname=2
ConfigurationParameter.Component.SlideItems.3.displayname=3
ConfigurationParameter.Component.SlideItems.4.displayname=4
ConfigurationParameter.Component.Title.description=Title for the displayed products (hidden if the list is empty)
ConfigurationParameter.Component.Title.displayname=Title
ListParameter.Component.ListItemStyle.defaultvalue=tile
ListParameter.Component.ListItemStyle.description=List item style (tile or row)
ListParameter.Component.ListItemStyle.displayname=List Item Style
ListParameter.Component.ListStyle.defaultvalue=none
ListParameter.Component.ListStyle.description=List style (plain product list or carousel)
ListParameter.Component.ListStyle.displayname=List Style
ListParameter.Component.SlideItems.defaultvalue=4
ListParameter.Component.SlideItems.description=Number of items per carousel slide (only relevant if carousel is selected)
ListParameter.Component.SlideItems.displayname=Slide Items
Pagelet.Component.description=Displays a list of products from a REST response
Pagelet.Component.displaygroup=Common
Pagelet.Component.displayname=Product List (REST)
Pagelet.Component.image=component.common.productListRest.svg
