// Public definitions of pages defined in this cartridge 
PageletACL.app_sf_base_cm\:page.helpdesk.pagelet2-Page.public=true
PageletACL.app_sf_base_cm\:page.privacyPolicy.pagelet2-Page.public=true
PageletACL.app_sf_base_cm\:page.termsAndConditions.pagelet2-Page.public=true