# Localizable properties associated with component.configuration.pagelet2

Pagelet.Component.description=Provide additional storefront configuration via CMS.
Pagelet.Component.displayname=Configuration
Pagelet.Component.displaygroup=Configuration
ConfigurationParameter.Component.Logo.displayname=Logo
ConfigurationParameter.Component.Logo.description=Brand logo for the storefront header
ConfigurationParameter.Component.LogoMobile.displayname=Logo (mobile)
ConfigurationParameter.Component.LogoMobile.description=Brand logo for the storefront header in mobile view
ConfigurationParameter.Component.Favicon.displayname=Favicon
ConfigurationParameter.Component.Favicon.description=Favicon for the storefront
ConfigurationParameter.Component.CSSProperties.displayname=CSS Properties
ConfigurationParameter.Component.CSSProperties.description=Set the PWA Theme CSS custom properties as multiline key value pairs without '--' (e.g., corporate-primary:#c36e68).
ConfigurationParameter.Component.CSSFonts.displayname=CSS Fonts
ConfigurationParameter.Component.CSSFonts.description=Integrate CSS Font references (multiline) (e.g., https://fonts.googleapis.com/css2?family=Open+Sans).
ConfigurationParameter.Component.Features.displayname=Features
ConfigurationParameter.Component.Features.description=Comma-separated list of activated features
ConfigurationParameter.Component.AddFeatures.description=Comma-separated list of additional features extending defaults
ConfigurationParameter.Component.AddFeatures.displayname=Additional Features
ConfigurationParameter.Component.ConfigurationJSON.displayname=Configuration JSON
ConfigurationParameter.Component.ConfigurationJSON.description=Generic additional configuration in JSON format
ConfigurationParameter.Component.CSSFile.displayname=CSS File
ConfigurationParameter.Component.CSSStyling.displayname=CSS Styling
ConfigurationParameter.Component.CSSStyling.description=Additional CSS style definitions
ConfigurationParameter.Component.CSSFile.description=Reference to an additional *.css file
Pagelet.Component.image=component.configuration.svg
