Class1 = com.intershop.component.foundation.dbmigrate.preparer.AddAttributeDescriptorPreparer \
           com.intershop.demo.responsive.catalog.dbinit.data.product.StandardBackofficeSearchAttributeDescriptors \
           com.intershop.demo.responsive.catalog.dbinit.data.product.StandardBackofficeSearchAttributeDescriptorsLocalization \
           inSPIRED-inTRONICS_Business