# Product data feeds updating LocaleID custom attribute
Class1 = com.intershop.component.mvc.dbmigrate.preparer.UpdateProductDataFeedPreparer \
           inSPIRED-inTRONICS \
           com.intershop.demo.responsive.catalog.dbinit.data.productdatafeed.StandardDataFeed \
           inTRONICS

Class2 = com.intershop.component.mvc.dbmigrate.preparer.UpdateProductDataFeedPreparer \
           inSPIRED-inTRONICS_Business \
           com.intershop.demo.responsive.catalog.dbinit.data.productdatafeed.StandardDataFeed \
           inTRONICS_Business