# disable deprecated code generation plugins 
disableStandardJaxb = true
disableStandardJavacc=true
disableStandardResourceListPlugin = true
disableStandardISML = true
disableStandardWSDL = true

# build configuration
org.gradle.parallel = true
org.gradle.workers.max = 5
org.gradle.configureondemand = false

# WebDriver versions used by the assembly Geb test configuration
chromeVersion = 2.29
geckoVersion = v0.19.1

# DO NOT MERGE THIS
# enable snapshot
#systemProp.enableSnapshots = true
# DO NOT MERGE THIS
org.gradle.configureondemand = false
