# sonar-project.properties

sonar.projectKey=anushreegupta14_intershop-cisetup-sources
sonar.organization=anushreegupta14

sonar.branch.name=developbranch
sonar.sources=intershop-cisetup-sources/intershop-cisetup-sources/projects/corporateshop/app_sf_rest_custom

# Path to JaCoCo XML report(s)
sonar.coverage.jacoco.xmlReportPaths=intershop-cisetup-sources/intershop-cisetup-sources/projects/corporateshop/app_sf_rest_custom/reports/jacoco/test/jacocoTestReport.xml

# Path to JUnit XML reports directory / files
sonar.junit.reportPaths=intershop-cisetup-sources/intershop-cisetup-sources/projects/corporateshop/app_sf_rest_custom/test-results
