# sonar-project.properties

sonar.projectKey=anushreegupta14_intershop-cisetup-sources
sonar.organization=anushreegupta14

sonar.branch.name=develop
sonar.sources=intershop-cisetup-sources/projects/corporateshop/app_sf_rest_custom
#e53fbf95a0b83c5c8a9cfeefb8225c761b72c8b6

