# Id of the platform to deploy on (must match the actual OS/distribution for the tests to be successful)
# Choose from: linux.rhel.x86_64, linux.sles.x86_64, win.x86_64
platformId = win.x86_64
# ID of the deployed server instance
instanceId = intershop
# Set environment for your deployment: production, test, development
environment = development
# Choose whether or not to deploy Javadoc for release cartridges
#includeJavadoc = false
# Configure the number of used application servers
numberOfAppservers = 1
# license
licenseFile = D:/ISH710/license.xml
# Important ports
webserverPort = 80
webserverHttpsPort = 443
appserverDebugPort = 6667
testrunnerDebugPort = 6668
dbToolDebugPort = 6669
eurekaServerPort = 8765
eurekaServerHostName = localhost
eurekaServerPath = eureka/
eurekaServerEnvironment = intershop
eurekaserverReplicaUrl = http://localhost:8765/eureka/
eurekaAppServerName = appServerName
microServicePort = 9123
microServiceName = Microservice
microServiceInstanceId = microServiceInstanceID
# Microservice database configuration
microserviceConnectionUrlDatabase = jdbc:oracle:thin:@localhost:1521:ORCL
microserviceUserDatabase = IS_MS
microservicePasswordDatabase = intershop
freePortsStart = 10050
freePortsEnd = 10059
# Database configuration
databaseHost = localhost
databasePort = 1521
databaseType = oracle
jdbcUrl = jdbc:oracle:thin:@localhost:1521:ORCL
databaseSid = ORCL
databaseTnsAlias = ISSERVER.world
databaseUser = intershop
databasePassword = INTERSHOP
oracleClientDir = D:/app/oracle/product/19.0.0/dbhome_1
# User group and user, uncomment and set on Linux
#user = isas1
#userGroup = isgrp1
# Multicast configuration
# Use the variable multicastIPSuffix to automatically configure your multicast
# configuration. Set your phone number to configure the last two bytes of the multicast IP, e.g. 12.34
multicastIPSuffix = 12.34
# Use different multicast ports for different deployments of yours
multicastPort = 50000
# To explicitly configure the multicast settings of your installation
# use the following properties.
#appserverMulticastAddress = 239.192.<4-digit phone suffix in groups of 2, e.g ##.##>
#appserverMulticastPort = 50000
#tcmMulticastAddress = 239.193.<4-digit phone suffix in groups of 2, e.g ##.##>
#tcmMulticastPort = 50000
#cacheMulticastAddress  = 239.194.<4-digit phone suffix in groups of 2, e.g ##.##>
#cacheMulticastPort = 50000
#ormMulticastAddress  = 239.195.<4-digit phone suffix in groups of 2, e.g ##.##>
#ormMulticastPort = 50000
webAdapterSharedMemoryKey = 0x2001
solrZooKeeperHostList = localhost:9983
clusterIndexPrefix = ICMDemoServer
