/** 
 * Generated 
 * Version   : 2.2.0
 * TimeStamp : 20170804125442
 *
 * Generation: 20180605071249
 **/

//See Gradle Documentation 'Initialization Scripts'
//definition of external dependencies
initscript {
  repositories {
    jcenter()
  }
  dependencies {
    //Repository configuration - provided by Intershop
    classpath 'com.intershop.gradle.repoconfig:repoconfig-gradle-plugin:3.3.0'
  }
}

// add configuration necessary for pre-project objects (like Gradle settings or init scripts)
apply plugin: com.intershop.gradle.repoconfig.RepoConfigPlugin

repositoryConfiguration {

     releaseRepo = 'http://bunzl-nexus.salnl.net/nexus/content/groups/components'
     snapshotRepo = 'http://bunzl-nexus.salnl.net/nexus/content/repositories/snapshots'

    // ivyReleaseRepo = 'http://bunzl-nexus.salnl.net/nexus/content/ivy-releases'
    // mvnReleaseRepo = 'http://bunzl-nexus.salnl.net/nexus/content/mvn-releases'
    // ivySnapshotRepo = 'http://bunzl-nexus.salnl.net/nexus/content/ivy-snapshots'
    // mvnSnapshotRepo = 'http://bunzl-nexus.salnl.net/nexus/content/mvn-snapshots'

    repoHostList = ['nexus']
    corporateName = 'test.corporatename'
}