# Localizable properties associated with include.configuration.pagelet2

ComponentEntryPoint.Include.description=Include to manage additional configuration for the Intershop PWA
ComponentEntryPoint.Include.displaygroup=Configuration
ComponentEntryPoint.Include.displayname=Configuration
